$(function(){"use strict";function scrolltop_arrow(){var scrollup=$('.scrollup');var headertag=$('header');var mainfix=$('.main');$(window).scroll(function(){if($(this).scrollTop()>0){scrollup.fadeIn(300);}else{scrollup.fadeOut(300);}
if($(this).scrollTop()>40){headertag.addClass("header-fixed");}
else{headertag.removeClass("header-fixed");}
if($(this).scrollTop()>0){mainfix.addClass("main-fixed");}
else{mainfix.removeClass("main-fixed");}});scrollup.on("click",function(){$("html, body").animate({scrollTop:0},1000);return false;});}
var inView=false;function isScrolledIntoView(elem){if($('#chartjs-doughnut').length>0){var docViewTop=$(window).scrollTop();var docViewBottom=docViewTop+$(window).height();var elemTop=$(elem).offset().top;var elemBottom=elemTop+$(elem).height();return((elemTop<=docViewBottom));}}
var chartexe=false;$(document).ready(function(){scrolltop_arrow();});$('.navbar-toggle').on("click",function(){var menu_id=$('#menu');var nav_icon=$('.navbar-toggle i');if(menu_id.hasClass('menu-open')){menu_id.removeClass('menu-open');nav_icon.removeClass('fa-times');nav_icon.addClass('fa-bars');}else{menu_id.addClass('menu-open');nav_icon.addClass('fa-times');nav_icon.removeClass('fa-bars');}
return false;});});$(window).on("load",function(){$(".se-pre-con").fadeOut("slow");});if(window.location.href.includes('profile')){jscolor.presets.default={format:'any'};}
function logout(){fetch('/api/logout')}
(function(b){b.toast=function(a,h,g,l,k){b("#toast-container").length||(b("body").prepend('<div id="toast-container" aria-live="polite" aria-atomic="true"></div>'),b("#toast-container").append('<div id="toast-wrapper"></div>'));var c="",d="",e="text-muted",f="",m="object"===typeof a?a.title||"":a||"Notice!";h="object"===typeof a?a.subtitle||"":h||"";g="object"===typeof a?a.content||"":g||"";k="object"===typeof a?a.delay||3E3:k||3E3;switch("object"===typeof a?a.type||"":l||"info"){case "info":c="bg-info";f=e=d="text-white";break;case "success":c="bg-success";f=e=d="text-white";break;case "warning":case "warn":c="bg-warning";f=e=d="text-white";break;case "error":case "danger":c="bg-danger",f=e=d="text-white"}a='<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="'+k+'">'+('<div class="toast-header '+c+" "+d+'">')+('<strong class="mr-auto">'+m+"</strong>");a+='<small class="'+e+'">'+h+"</small>";a+='<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">';a+='<span aria-hidden="true" class="'+f+'">&times;</span>';a+="</button>";a+="</div>";""!==g&&(a+='<div class="toast-body">',a+=g,a+="</div>");a+="</div>";b("#toast-wrapper").append(a);b("#toast-wrapper .toast:last").toast("show")}})(jQuery);