(function($){'use strict';var I18N,slice=Array.prototype.slice;I18N=function(options){this.options=$.extend({},I18N.defaults,options);this.parser=this.options.parser;this.locale=this.options.locale;this.messageStore=this.options.messageStore;this.languages={};};I18N.prototype={localize:function(messageKey){var localeParts,localePartIndex,locale,fallbackIndex,tryingLocale,message;locale=this.locale;fallbackIndex=0;while(locale){localeParts=locale.split('-');localePartIndex=localeParts.length;do{tryingLocale=localeParts.slice(0,localePartIndex).join('-');message=this.messageStore.get(tryingLocale,messageKey);if(message){return message;}
localePartIndex--;}while(localePartIndex);if(locale===this.options.fallbackLocale){break;}
locale=($.i18n.fallbacks[this.locale]&&$.i18n.fallbacks[this.locale][fallbackIndex])||this.options.fallbackLocale;$.i18n.log('Trying fallback locale for '+this.locale+': '+locale+' ('+messageKey+')');fallbackIndex++;}
return '';},destroy:function(){$.removeData(document,'i18n');},load:function(source,locale){var fallbackLocales,locIndex,fallbackLocale,sourceMap={};if(!source&&!locale){source='i18n/'+$.i18n().locale+'.json';locale=$.i18n().locale;}
if(typeof source==='string'&&source.split('?')[0].split('.').pop()!=='json'){sourceMap[locale]=source+'/'+locale+'.json';fallbackLocales=($.i18n.fallbacks[locale]||[]).concat(this.options.fallbackLocale);for(locIndex=0;locIndex<fallbackLocales.length;locIndex++){fallbackLocale=fallbackLocales[locIndex];sourceMap[fallbackLocale]=source+'/'+fallbackLocale+'.json';}
return this.load(sourceMap);}else{return this.messageStore.load(source,locale);}},parse:function(key,parameters){var message=this.localize(key);this.parser.language=$.i18n.languages[$.i18n().locale]||$.i18n.languages['default'];if(message===''){message=key;}
return this.parser.parse(message,parameters);}};$.i18n=function(key,param1){var parameters,i18n=$.data(document,'i18n'),options=typeof key==='object'&&key;if(options&&options.locale&&i18n&&i18n.locale!==options.locale){i18n.locale=options.locale;}
if(!i18n){i18n=new I18N(options);$.data(document,'i18n',i18n);}
if(typeof key==='string'){if(param1!==undefined){parameters=slice.call(arguments,1);}else{parameters=[];}
return i18n.parse(key,parameters);}else{return i18n;}};$.fn.i18n=function(){var i18n=$.data(document,'i18n');if(!i18n){i18n=new I18N();$.data(document,'i18n',i18n);}
return this.each(function(){var $this=$(this),messageKey=$this.data('i18n'),lBracket,rBracket,type,key;if(messageKey){lBracket=messageKey.indexOf('[');rBracket=messageKey.indexOf(']');if(lBracket!==-1&&rBracket!==-1&&lBracket<rBracket){type=messageKey.slice(lBracket+1,rBracket);key=messageKey.slice(rBracket+1);if(type==='html'){$this.html(i18n.parse(key));}else{$this.attr(type,i18n.parse(key));}}else{$this.text(i18n.parse(messageKey));}}else{$this.find('[data-i18n]').i18n();}});};function getDefaultLocale(){var locale=$('html').attr('lang');if(!locale){locale=navigator.language||navigator.userLanguage||'';}
return locale;}
$.i18n.languages={};$.i18n.messageStore=$.i18n.messageStore||{};$.i18n.parser={parse:function(message,parameters){return message.replace(/\$(\d+)/g,function(str,match){var index=parseInt(match,10)-1;return parameters[index]!==undefined?parameters[index]:'$'+match;});},emitter:{}};$.i18n.fallbacks={};$.i18n.debug=false;$.i18n.log=function(){if(window.console&&$.i18n.debug){window.console.log.apply(window.console,arguments);}};I18N.defaults={locale:getDefaultLocale(),fallbackLocale:'en',parser:$.i18n.parser,messageStore:$.i18n.messageStore};$.i18n.constructor=I18N;}(jQuery));